Davydova_Task4_Library.WebUI/Controllers/BookController.cs
using Davydova_Task4_Library.BLL.Implementations;
using Davydova_Task4_Library.BLL.Interfaces;
using Davydova_Task4_Library.WebUI.Models.Book;
using Davydova_Task4_Library.WebUI.Models.BookViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Serilog.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Davydova_Task4_Library.WebUI.Controllers
{
    public class BookController : Controller
    {
        private IBookLogic _bookLogic;
        private readonly ILogger<BookLogic> _logger;

        public BookController(IBookLogic bookLogic, ILogger<BookLogic> logger)
        {
            _bookLogic = bookLogic;
            _logger = logger;
        }

       // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                return View(_bookLogic.GetBookById(id));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return RedirectToAction("Index", "LibraryObject");
            }
        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateBook book)
        {
            try
            {
                _bookLogic.AddBook(book.Name, book.CountOfPages, book.Note, book.PlaceOfPublication, book.PublishingHouse, book.PublicationYear, book.Authors, book.ISBN);
                return RedirectToAction("Index", "LibraryObject");
            }
            catch (Exception ex)
            {
                _logger.LogError("Creating was wrong" + ex.Message);
                return View();
            }
        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                return View(_bookLogic.GetBookById(id));
            }
            catch (Exception ex)
            {
                _logger.LogInformation("Editing was wrong " + ex.Message);
                return RedirectToAction("Index", "LibraryObject");
            }
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditBook book)
        {
            try
            {
                _bookLogic.UpdateBook(book.Id, book.Name, book.CountOfPages, book.Note, book.PlaceOfPublication, book.PublishingHouse, book.PublicationYear, book.Authors, book.ISBN);
                return RedirectToAction("Index", "PrintEdition");
            }
            catch
            {
                _logger.LogInformation("Editing was wrong");
                return RedirectToAction("Index", "LibraryObject");
            }
        }

        // GET: BookController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                return View(_bookLogic.GetBookById(id));
            }
            catch (Exception ex)
            {
                _logger.LogError("Deleting was wrong" + ex.Message);
                return RedirectToAction("Details", "Book", id);
            }
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(GetBook book)
        {
            try
            {
                _bookLogic.DeleteBook(book.Id);
                return RedirectToAction("Index", "LibraryObject");
            }
            catch (Exception ex)
            {
                _logger.LogError("Deleting was wrong" + ex.Message);
                return View();
            }
        }
    }
}

Davydova_Task4_Library.WebUI/ViewComponents/DropdownMultiSelectViewComponent.cs
using Davydova_Task4_Library.BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Davydova_Task4_Library.WebUI.ViewComponents
{
    public class DropdownMultiSelectViewComponent:ViewComponent
    {
        private IAuthorLogic _authorLogic;

        public DropdownMultiSelectViewComponent(IAuthorLogic authorLogic)
        {
            _authorLogic = authorLogic;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.ListOfAuthors = new MultiSelectList(_authorLogic.GetAllAuthors(), "Id", "FullName");
            return View();
        }
    }
}

Davydova_Task4_Library.WebUI/Views/Book/Create.cshtml
@model Davydova_Task4_Library.WebUI.Models.Book.CreateBook

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CreateBook</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfPublication" class="control-label"></label>
                <input asp-for="PlaceOfPublication" class="form-control" />
                <span asp-validation-for="PlaceOfPublication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingHouse" class="control-label"></label>
                <input asp-for="PublishingHouse" class="form-control" />
                <span asp-validation-for="PublishingHouse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicationYear" class="control-label"></label>
                <input asp-for="PublicationYear" class="form-control" />
                <span asp-validation-for="PublicationYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountOfPages" class="control-label"></label>
                <input asp-for="CountOfPages" class="form-control" />
                <span asp-validation-for="CountOfPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div id="component-block">
                @await Component.InvokeAsync("DropdownMultiSelect")
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="col-md-3">
    @await Component.InvokeAsync("AjaxCreateAuthor")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Davydova_Task4_Library.WebUI/Views/Book/Details.cshtml
@using Davydova_Task4_Library.BLL.Interfaces
@model Davydova_Task4_Library.WebUI.Models.BookViewModels.GetBook
@inject IBookLogic _bookLogic

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>GetBook</h4>
    <hr />
    <dl class="row">
        <dt>Authors:</dt>
        <dd>
            @{
                System.Text.StringBuilder sb = new System.Text.StringBuilder();
                foreach (var author in _bookLogic.GetAuthorsByBookId(Model.Id))
                {
                    Model.Authors.Add(author);
                    sb.Append(author.Name);
                    sb.Append(" ");
                    sb.Append(author.Surname);
                    sb.Append(" ");
                }
                <p>@sb.ToString()</p>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceOfPublication)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlaceOfPublication)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingHouse)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishingHouse)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublicationYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublicationYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CountOfPages)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CountOfPages)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Back to list", "Index", "LibraryObject") |
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Delete", "Delete", "Book", new { id = Model.Id }, null)
</div>